### ISSUE TITLE
factor out deep-dictionary merging/interpolation core from the ENC that is the rest of reclass

### ISSUE THREAD

**Issue by iluminite** [madduck/reclass#37]
This isn't to be done until the dust from the existing refactor (#30) settles and clears.

Madduck also noted that we'd want to re-enable/extend different merging policies, see: https://github.com/madduck/reclass/blob/ff1342cbbb6f5c302abcf0f5cdfab0c38f6432b6/reclass/datatypes/parameters.py#L142

The idea is to make the core dictionary merging a reusable component, in a separate library that Reclass (the External Node Classifier) uses. Other python projects could then make use of this library as well, for deep-dictionary merging and interpolation.. I know I want to use it!

**Comment by Rtzq0** [comment]
closing this issue as originating user is inactive
