### ISSUE TITLE
Remove application in class

### ISSUE THREAD

**Issue by afletch** [madduck/reclass#44]
I would expect that when an applications uses ~ prefix, when inside a class definition, this would be removed from the application list, but it does not appear to be the case. eg.

nodes/my.node.com.yml:

```
classes:
  - include_class
  - exclude_class
```

classes/include_class.yml

```
applications:
  - myformula
```

classes/exclude_class.yml

```
applications:
  - ~myformula
```

reclass-salt --pillar my.node.com

```
..
"applications": [
  "myapp"
],
```

**Comment by madduck** [comment]
Ouch! +1 for fixing integration tests.
And thanks for the bug report.

This one seems easy to fix. Could you try the attached^Winlined patch, please?¹

    diff --git a/reclass/datatypes/applications.py b/reclass/datatypes/applications.py
    index d024e97..63c2393 100644
    --- a/reclass/datatypes/applications.py
    +++ b/reclass/datatypes/applications.py
    @@ -53,6 +53,7 @@ class Applications(Classes):
                        self._items.remove(negation)
                    except ValueError:
                        pass
    +            self._negations.extend(iterable._negations)
                iterable = iterable.as_list()
            for i in iterable:
                self.append_if_new(i)

¹) OMFG Github does not allow attaching patches.

**Comment by afletch** [comment]
Perfect, thanks.

**Comment by lottspot** [comment]
Looks like there's no reason not to apply this patch. We'll work on getting this fix integrated soon.
