### ISSUE TITLE
No timezone in output of timestamp

### ISSUE THREAD

**Issue by jimcheetham** [madduck/reclass#50]
Running from the cli, there is a timestamp value in the output, and although this does correctly follow the environment's TZ setting the timezone of the value is not explicitly displayed.

This can be fixed in reclass/core.py:Core._get_timestamp() which currently returns time.strftime('%c'), by changing the strftime format to '%c %Z' (this is a small change, and not worth an explicit pull request!)

This change probably has no negative impact if the only consumer of the output is human, but I see adapters calling reclass.inventory(), and it might affect them ...

**Comment by ub1quit33** [comment]
What's wrong with querying the system to figure out what TZ you're in if you need to know that? This doesn't strike me as reclass's problem, and I doubt the maintainer will have much interest in making that change

**Comment by lottspot** [comment]
This change carries breakage potential with little if any benefit. If someone presents a valid usecase for making this change, we can revisit the issue, but otherwise this is not a change we'll be dedicating time to implementing.
