### ISSUE TITLE
Maintainers for the Python PyPI package

### ISSUE THREAD

**Issue by ademariag** [madduck/reclass#86]
Hello, we have been maintaining a fork (https://github.com/kapicorp/reclass) of this repository and https://github.com/salt-formulas/reclass.

We use reclass as part of our https://kapitan.dev project

Both seem unmaintained. Is there any chance for us to become maintainers of the PyPI package? https://pypi.org/project/reclass/ currently maintained by https://pypi.org/user/lottspot/ (@lottspot  ?) and https://pypi.org/user/rtzq0/ (@Rtzq0 ?)

If you are ok with it, please add https://pypi.org/user/ademaria/ and https://pypi.org/user/ramaro/

**Comment by madduck** [comment]
I don't have a problem with that, and I welcome you reaching out.

**Comment by ademariag** [comment]
Thank you @madduck, we've been using your project for a very long time and it's been extremely helpful. thank you so much for it

**Comment by ademariag** [comment]
Hello, we have decided to create our own package https://pypi.org/project/kapicorp-reclass/2.0.0/ so to avoid confusion, because we might have some backward incompatible features.

thank you

**Comment by lottspot** [comment]
@ademariag I believe I still have access to the current pypi package. Let me double check that and then figure out how to turn over the package if I in fact do.
